name: Auto-merge polukay556 PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    if: github.actor == 'polukay556'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve PR from polukay556
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Auto-merge PR
        uses: pascalgn/merge-action@v0.15.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          merge_commit_title: "{pull_request.title} (#{pull_request.number})"

  route-papaert-to-review:
    if: github.actor == 'papaert-cloud' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR and redirect to VS-CODE-commit
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              base: 'VS-CODE-commit'
            });
